services:
  backend:
    build: ./backend
    container_name: mini-rag-backend
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
    networks:
      - rag-network

  frontend:
    build:
      context: ./frontend
      args:
        REACT_APP_API_URL: http://backend:8000
    container_name: mini-rag-frontend
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://backend:8000
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - rag-network

networks:
  rag-network:
    driver: bridge 