services:
  backend:
    build: ./backend
    container_name: mini-rag-backend
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
    networks:
      - rag-network

  minio:
    image: minio/minio:latest
    container_name: mini-rag-minio
    ports:
      - "9000:9000"  # MinIO API
      - "9001:9001"  # MinIO Console
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin123
      MINIO_CONSOLE_ADDRESS: ":9001"
    volumes:
      - minio_data:/data
      - ./minio-init:/docker-entrypoint-initdb.d
    command: server /data --console-address ":9001"
    restart: unless-stopped
    networks:
      - rag-network

  chromadb:
    image: chromadb/chroma:latest
    container_name: mini-rag-chromadb
    ports:
      - "8001:8000"  # ChromaDB API (mapped to host port 8001)
    environment:
      - CHROMA_SERVER_HOST=0.0.0.0
      - CHROMA_SERVER_HTTP_PORT=8000
      - CHROMA_SERVER_CORS_ALLOW_ORIGINS=["*"]
    volumes:
      - chromadb_data:/chroma/chroma
    restart: unless-stopped
    networks:
      - rag-network

  frontend:
    build:
      context: ./frontend
      args:
        REACT_APP_API_URL: http://backend:8000
    container_name: mini-rag-frontend
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://backend:8000
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - rag-network

networks:
  rag-network:
    driver: bridge

volumes:
  minio_data:
  chromadb_data: 